// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_thats_a_start = "CgkIqK61pYkHEAIQDw"; // <GPGSID>
        public const string leaderboard_all_time_most_jewels_collected = "CgkIqK61pYkHEAIQGA"; // <GPGSID>
        public const string achievement_what_is_this_for = "CgkIqK61pYkHEAIQEw"; // <GPGSID>
        public const string achievement_precision = "CgkIqK61pYkHEAIQDQ"; // <GPGSID>
        public const string leaderboard_all_time_most_bullseyes_hit = "CgkIqK61pYkHEAIQFw"; // <GPGSID>
        public const string achievement_golden_delicious_the_west_virginia_hasbeen = "CgkIqK61pYkHEAIQBg"; // <GPGSID>
        public const string achievement_precisionist = "CgkIqK61pYkHEAIQDg"; // <GPGSID>
        public const string achievement_robin_hood = "CgkIqK61pYkHEAIQEg"; // <GPGSID>
        public const string leaderboard_all_time_most_targets_hit = "CgkIqK61pYkHEAIQFg"; // <GPGSID>
        public const string achievement_perfection = "CgkIqK61pYkHEAIQCg"; // <GPGSID>
        public const string achievement_red_delicious_coffee_grinds_in_a_leather_glove = "CgkIqK61pYkHEAIQBQ"; // <GPGSID>
        public const string achievement_now_you_are_getting_somewhere = "CgkIqK61pYkHEAIQEQ"; // <GPGSID>
        public const string achievement_bullseye = "CgkIqK61pYkHEAIQFA"; // <GPGSID>
        public const string achievement_perfect = "CgkIqK61pYkHEAIQCQ"; // <GPGSID>
        public const string achievement_granny_smith_the_original_sour_apple = "CgkIqK61pYkHEAIQBw"; // <GPGSID>
        public const string leaderboard_all_time_most_points = "CgkIqK61pYkHEAIQAQ"; // <GPGSID>
        public const string achievement_perfectionist = "CgkIqK61pYkHEAIQCw"; // <GPGSID>
        public const string achievement_keep_it_up = "CgkIqK61pYkHEAIQEA"; // <GPGSID>
        public const string achievement_honey_crisp_the_worldwide_favorite = "CgkIqK61pYkHEAIQCA"; // <GPGSID>
        public const string leaderboard_all_time_most_arrows_fired = "CgkIqK61pYkHEAIQFQ"; // <GPGSID>
        public const string achievement_precise = "CgkIqK61pYkHEAIQDA"; // <GPGSID>

}

